# Generated by Django 3.2.6 on 2021-09-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dd2app', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
